# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main
- feature/deployment

pool:
   vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build the App

  jobs:
  - job: Build_Go_App
    displayName: Build Go App
    steps: 
     - task: GoTool@0
       displayName: Install Go
       inputs:
        version: '1.18.2'

     - task: Go@0
       displayName: Get dependencies
       inputs:
         command: 'get'
         arguments: '-d'
         workingDirectory: '$(System.DefaultWorkingDirectory)'

     - task: Go@0
       displayName: Build the App
       inputs:
         command: 'build'
         workingDirectory: '$(System.DefaultWorkingDirectory)'

     - task: CopyFiles@2
       displayName: Copy to Staging Dir
       inputs:
         Contents: "azure-multi-region-ref-arch*"
         TargetFolder: '$(Build.ArtifactStagingDirectory)'

     - task: PublishBuildArtifacts@1
       displayName: Publish artifacts
       inputs:
         artifactName: drop

- stage: Deploy
  displayName: Deploy the App
  jobs:
  - deployment:
    displayName: Deploy Go App
    environment:
      name:  az-multi-region-env
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: sudo mv $(Agent.BuildDirectory)/drop/azure-multi-region-ref-arch /opt/
            displayName: "Moving to /opt"
          - script: ls /opt/opt/azure-multi-region-ref-arch
            displayName: "Starting App"