# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- main

pool:
   vmImage: 'windows-latest'

steps: 
- task: GoTool@0
  displayName: Install Go
  inputs:
    version: '1.18.2'
- task: Go@0
  displayName: Get dependencies
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: Build the App
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  displayName: Copy to Staging Dir
  inputs:
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publish artifacts
  inputs:
     artifactName: drop